JavaScript Templating is the best way to turn AJAX/JSON data into HTML. *Jemplate* is the best way to do JavaScript Templating.

*Jemplate* beats other JavaScript Templating frameworks hands down for the following reasons:

* Jemplate is a complete port of the popular "Template Toolkit"<http://www.template-toolkit.org/> framework. This means it is very full featured indeed.
* Templates are precompiled (one time, on the server) as JavaScript functions. There is no JavaScript runtime penalty of compiling templates.
* Templates are *not* stored in your HTML. No silly tricks, like putting template code in hidden textareas.
* A browser downloads your templates once and caches them. Just like any other JavaScript code.

This site is generated entirely by Jemplate. View Source to see for yourself.

> -- Ingy döt Net

